name: Run Tests on Pull Request

on:
  pull_request:  # Trigger this workflow on pull requests
    branches:
      - main  # Or the branch you're merging into

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Run your test script
    - name: Run tests
      run: |
        pytest -v -s tests/
